name: Release Build

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "./webapp/package-lock.json"

      - name: Build plugin
        run: |
          make all

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.tar.gz
          name: ${{ github.ref_name }}
          body: |
            ## Changes

            This release includes:
            - Plugin version: ${{ github.ref_name }}

            ## Installation

            1. Download the attached `mattermost-quote-plugin-*.tar.gz`
            2. Go to Mattermost System Console > **Plugin Management > Upload Plugin**
            3. Upload the plugin file
            4. Enable the plugin
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
